Update hydra
Proph151 Edits...

1. check_if_github_token_is_valid() - Prompt will ask if no token is found in the .ENV file.

2. update_env_file() - Will add edits to the .ENV file if given through prompts.

3. update_p12_info() - Prompts to update P12 info in the .ENV file if the defaults are found.

4. install() - If defaults are found within the .ENV file prompts will be asked which can update the .ENV file.

5. build() - Custom P12 files will be automatically created if the P12 files referenced within the .ENV file are not found in the location.

diff --git a/scripts/hydra b/scripts/hydra
--- a/scripts/hydra
+++ b/scripts/hydra
@@ -32,7 +32,18 @@ check_if_docker_is_running() {
 check_if_github_token_is_valid() {
   if curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user | grep -q "Bad credentials"; then
     echo "Invalid GITHUB_TOKEN"
-    exit 1
+    echo ""
+    printf "\033[93mEnter a valid GitHub token.\033[0m"
+    read -r new_token
+    if [[ ! -z "$new_token" ]]; then
+      GITHUB_TOKEN="$new_token"
+      update_env_file "GITHUB_TOKEN" "$new_token"
+      echo ""
+      printf "Updated value for GITHUB_TOKEN is: \033[32m$GITHUB_TOKEN\033[0m"
+      check_if_github_token_is_valid
+    else
+      exit 1
+    fi
   fi
 }
 
@@ -120,6 +131,54 @@ stop_container() {
   $dockercompose stop
   cd ../../../
   echo "$1 container stopped"
+}
+
+# @cmd Installs a local framework and detaches project
+install() {
+  BASEDIR=$(dirname "$0")
+  cd $BASEDIR
+
+  if [ -d "scripts" ]; then
+    cd scripts/
+  fi
+
+  source ../.env
+
+  cd ../
+
+  check_if_github_token_is_valid
+  check_if_project_name_is_set
+
+  if [[ "$PROJECT_NAME" == "custom-project" ]]; then
+    update_p12_info "PROJECT_NAME" "$PROJECT_NAME" "The project name is currently set to the default setting:" "Project name should not contain spaces. Please enter a new value or just press Enter:"
+  fi
+
+  if [[ "$P12_GENESIS_FILE_NAME" == "token-key.p12" ]]; then
+    update_p12_info "P12_GENESIS_FILE_NAME" "$P12_GENESIS_FILE_NAME" "You are currently using the default SDK P12_GENESIS_FILE_NAME:" "The P12 filename should not contain spaces. Please enter a new value or just press Enter:"
+  fi
+
+  if [[ "$P12_GENESIS_FILE_NAME" != "token-key.p12" ]]; then
+    update_p12_info "P12_GENESIS_FILE_KEY_ALIAS" "$P12_GENESIS_FILE_KEY_ALIAS" "Current value of the P12_GENESIS_FILE_KEY_ALIAS is:" "The P12 alias should not contain spaces. Please enter a new value or just press Enter:"
+    update_p12_info "P12_GENESIS_FILE_PASSWORD" "$P12_GENESIS_FILE_PASSWORD" "Current value of the P12_GENESIS_FILE_PASSWORD is:" "The P12 password should not contain spaces. Please enter a new value or just press Enter:"
+  fi
+
+  if [[ "$P12_NODE_2_FILE_NAME" == "token-key-1.p12" ]]; then
+    update_p12_info "P12_NODE_2_FILE_NAME" "$P12_NODE_2_FILE_NAME" "You are currently using the default SDK P12_NODE_2_FILE_NAME:" "The P12 filename should not contain spaces. Please enter a new value or just press Enter:"
+  fi
+
+  if [[ "$P12_NODE_3_FILE_NAME" == "token-key-2.p12" ]]; then
+    update_p12_info "P12_NODE_3_FILE_NAME" "$P12_NODE_3_FILE_NAME" "You are currently using the default SDK P12_NODE_3_FILE_NAME:" "The P12 filename should not contain spaces. Please enter a new value or just press Enter:"
+  fi
+
+  echo "Installing hydra ..."
+  echo "Installing Framework..."
+  create_template project $PROJECT_NAME
+  chmod a+rwx infra/docker/monitoring/grafana/storage
+  if [ -d ".git" ]; then
+    chmod -R +w .git
+    rm -r .git
+  fi
+  echo "Installed"
 }
 
 join_l1_currency_nodes() {
@@ -229,6 +288,38 @@ check_if_project_directory_exists() {
     exit 1
   fi
   cd ..
+}
+
+update_env_file() {
+  # If the key exists in the .env file, update its value
+  if grep -q "^$key=" "$env_file"; then
+    # For GNU sed (Linux)
+    if sed --version &>/dev/null; then
+      sed -i "s/^$key=.*/$key=$value/" "$env_file"
+    # For BSD sed (macOS)
+    else
+      sed -i '' "s/^$key=.*/$key=$value/" "$env_file"
+    fi
+  fi
+}
+
+update_p12_info() {
+ printf "\033[93m%s [\033[32m%s\033[93m]\033[0m\n" "$prompt_message" "$current_value"
+  echo "Enter a new value or just press Enter:"
+  while true; do
+    read -r new_value
+    if [[ "$new_value" == *' '* ]]; then
+      echo "$error_message"
+    else
+      break
+    fi
+  done
+
+  if [[ ! -z "$new_value" ]]; then
+    update_env_file "$env_var_name" "$new_value"
+    echo ""
+    printf "Updated value for %s is: \033[32m%s\033[0m\n" "$env_var_name" "$new_value"
+  fi
 }
 
 start_containers(){
@@ -420,24 +511,73 @@ build() {
     exit 1
   fi
 
+  echo ""
+  echo "Verifying P12 files are available"
   if [[ -z "$argc_only" || "$argc_only" != "monitoring" ]]; then
-    echo
-    echo "P12 files should be inserted on source/p12-files directory"
     if [ ! -f "../source/p12-files/$P12_GENESIS_FILE_NAME" ]; then
-      echo "File does not exists"
-      exit 1
+      echo "  File missing: source/p12-files/$P12_GENESIS_FILE_NAME"
+      echo "    Attempting to create P12 file: $P12_GENESIS_FILE_NAME"
+      if [ ! -f "./cl-keytool.jar" ]; then
+        wget -q https://github.com/Constellation-Labs/tessellation/releases/download/v1.11.0/cl-keytool.jar
+      fi
+      export CL_KEYSTORE="$P12_GENESIS_FILE_NAME"
+      export CL_KEYALIAS="$P12_GENESIS_FILE_KEY_ALIAS"
+      export CL_PASSWORD="$P12_GENESIS_FILE_PASSWORD"
+      java -jar cl-keytool.jar generate
+      if [ ! -f "$P12_GENESIS_FILE_NAME" ]; then
+        echo "    Failed to create P12 file: $P12_GENESIS_FILE_NAME"
+        rm ./cl-keytool.jar
+        exit
+      fi
+      mv "$P12_GENESIS_FILE_NAME" "../source/p12-files/"
+      echo "    File created: source/p12-files/$P12_GENESIS_FILE_NAME"
+    else
+      echo "  File found: source/p12-files/$P12_GENESIS_FILE_NAME"
     fi
-
     if [[ -z "$argc_only" || "$argc_only" == "dag-l1" || "$argc_only" == "currency-l1" || ! -z "$argc_include_dag_l1" ]]; then
       if [ ! -f "../source/p12-files/$P12_NODE_2_FILE_NAME" ]; then
-        echo "File does not exists"
-        exit 1
+        echo "  File missing: source/p12-files/$P12_NODE_2_FILE_NAME"
+        echo "    Attempting to create P12 file: $P12_NODE_2_FILE_NAME"
+        if [ ! -f "./cl-keytool.jar" ]; then
+          wget -q https://github.com/Constellation-Labs/tessellation/releases/download/v1.11.0/cl-keytool.jar
+        fi
+        export CL_KEYSTORE="$P12_NODE_2_FILE_NAME"
+        export CL_KEYALIAS="$P12_NODE_2_FILE_KEY_ALIAS"
+        export CL_PASSWORD="$P12_NODE_2_FILE_PASSWORD"
+        java -jar cl-keytool.jar generate
+        if [ ! -f "$P12_NODE_2_FILE_NAME" ]; then
+          echo "    Failed to create P12 file: $P12_NODE_2_FILE_NAME"
+          rm ./cl-keytool.jar
+          exit
+        fi
+        mv "$P12_NODE_2_FILE_NAME" "../source/p12-files/"
+        echo "    File created: source/p12-files/$P12_NODE_2_FILE_NAME"
+      else
+        echo "  File found: source/p12-files/$P12_NODE_2_FILE_NAME"
       fi
-
       if [ ! -f "../source/p12-files/$P12_NODE_3_FILE_NAME" ]; then
-        echo "File does not exists"
-        exit 1
+        echo "  File missing: source/p12-files/$P12_NODE_3_FILE_NAME"
+        echo "    Attempting to create P12 file: $P12_NODE_3_FILE_NAME"
+        if [ ! -f "./cl-keytool.jar" ]; then
+          wget -q https://github.com/Constellation-Labs/tessellation/releases/download/v1.11.0/cl-keytool.jar
+        fi
+        export CL_KEYSTORE="$P12_NODE_3_FILE_NAME"
+        export CL_KEYALIAS="$P12_NODE_3_FILE_KEY_ALIAS"
+        export CL_PASSWORD="$P12_NODE_3_FILE_PASSWORD"
+        java -jar cl-keytool.jar generate
+        if [ ! -f "$P12_NODE_3_FILE_NAME" ]; then
+          echo "    Failed to create P12 file: $P12_NODE_3_FILE_NAME"
+          rm ./cl-keytool.jar
+          exit
+        fi
+        mv "$P12_NODE_3_FILE_NAME" "../source/p12-files/"
+        echo "    File created: source/p12-files/$P12_NODE_3_FILE_NAME"
+      else
+        echo "  File found: source/p12-files/$P12_NODE_3_FILE_NAME"
       fi
+    fi
+    if [ -e "./cl-keytool.jar" ]; then
+      rm ./cl-keytool.jar > /dev/null 2>&1
     fi
   fi
 
